#!/bin/bash

INST_LOG="/tmp/omniedge_install.log"
INST_VAR="${SYNOPKG_PKGDEST}/var"
TMP_DIR="${SYNOPKG_TEMP_UPGRADE_FOLDER}/var"
TARGET_PATH="/var/packages/${SYNOPKG_PKGNAME}/target"

logstep() { # <step_name>
  local date=$(date --iso-8601=second)
  echo -e "\n>> ${date} :: $1" >>${INST_LOG} 2>&1
}

postinst() {
  logstep "postinst"
  echo "NETWORK_ID=${omniedge_network_id}" > ${INST_VAR}/dialog 2>&1
  echo "SECURITY_KEY=${omniedge_security_key}" >> ${INST_VAR}/dialog 2>&1
}

postuninst() {
  logstep "postuninst"
}

preupgrade(){
  logstep "preupgrade"

  rm -vrf ${TMP_DIR} >>${INST_LOG} 2>&1
  mkdir -vp ${TMP_DIR} >>${INST_LOG} 2>&1

  echo "cp -rfp \"${INST_VAR}\"/. \"${TMP_DIR}\"" >>$INST_LOG
  cp -rfp "${INST_VAR}"/. "${TMP_DIR}" >>${INST_LOG} 2>&1
}

postupgrade() {
  logstep "postupgrade"

  echo "cp -rfp \"${TMP_DIR}\"/. \"${INST_VAR}\"" >>$INST_LOG
  cp -vrfp "${TMP_DIR}"/. "${INST_VAR}" >>$INST_LOG 2>&1
}
