#!/bin/bash

INST_LOG="/tmp/omniedge_install.log"
INST_VAR="${SYNOPKG_PKGDEST}/var"
TMP_DIR="${SYNOPKG_TEMP_UPGRADE_FOLDER}/var"
TARGET_PATH="/var/packages/${SYNOPKG_PKGNAME}/target"

logstep() { # <step_name>
  local date=$(date --iso-8601=second)
  echo -e "\n>> ${date} :: $1" >>${INST_LOG} 2>&1
}

postinst() {
  logstep "postinst"

  mkdir -vp $TARGET_PATH/var >>${INST_LOG} 2>&1
  mkdir -vp /usr/local/bin >>${INST_LOG} 2>&1

  chmod -v a+x /usr/local/bin/omniedge >>${INST_LOG} 2>&1
}

postuninst() {
  logstep "postuninst"

  rm -v /usr/local/bin/omniedge >>${INST_LOG} 2>&1
}

preupgrade(){
  logstep "preupgrade"

  rm -vrf ${TMP_DIR} >>${INST_LOG} 2>&1
  mkdir -vp ${TMP_DIR} >>${INST_LOG} 2>&1

  echo "cp -rfp \"${INST_VAR}\"/. \"${TMP_DIR}\"" >>$INST_LOG
  cp -rfp "${INST_VAR}"/. "${TMP_DIR}" >>${INST_LOG} 2>&
}

postupgrade() {
  logstep "postupgrade"

  echo "cp -rfp \"${TMP_DIR}\"/. \"${INST_VAR}\"" >>$INST_LOG
  cp -vrfp "${TMP_DIR}"/. "${INST_VAR}" >>$INST_LOG 2>&1
}
