#!/bin/bash

SERVICE="omniedge"
COMMAND="/usr/local/bin/omniedge"
PID_FILE="${SYNOPKG_PKGDEST}/var/omniedge.pid"
LOG_FILE="${SYNOPKG_PKGDEST}/var/omniedge.log"
DIALOG_FILE="/var/packages/omniedge/dialog"

if [ -f "${DIALOG_FILE}" ]; then
    . ${DIALOG_FILE}
fi

start() {
  echo "=== Starting ${SERVICE_NAME} with: ${SERVICE_COMMAND} login" >>${LOG_FILE}
  ${SERVICE_COMMAND} login -s ${SECURITY_KEY} -f /var/packages/omniedge/auth.json >>${LOG_FILE} 2>&1

  echo "=== Starting ${SERVICE_NAME} with: ${SERVICE_COMMAND} join" >>${LOG_FILE}
  ${SERVICE_COMMAND} join -n ${NETWORK_ID} -f /var/packages/omniedge/auth.json >>${LOG_FILE} 2>&1 &
  if [ -n "${PID_FILE}" ]; then
    echo "$!" >"${PID_FILE}"
  fi
}

stop() {
  if [ -n "${PID_FILE}" -a -r "${PID_FILE}" ]; then
    local PID=$(cat "${PID_FILE}")
    echo "=== Stopping ${SERVICE_NAME} service PID=${PID}" >>${LOG_FILE}
    kill -TERM $PID >>${LOG_FILE} 2>&1
    if [ -f "${PID_FILE}" ]; then
      rm -f "${PID_FILE}" >/dev/null
    fi
  fi
}

tun_created() {
    if ([ ! -c /dev/net/tun ]); then
        if ([ ! -d /dev/net ]); then
            mkdir -m 755 /dev/net
        fi
        mknod /dev/net/tun c 10 200
        chmod 0755 /dev/net/tun
    fi

    if (!(lsmod | grep -q "^tun\s")); then
        insmod /lib/modules/tun.ko
    fi
}

status() {
  if [ -n "${PID_FILE}" -a -r "${PID_FILE}" ]; then
    local PID=$(cat "${PID_FILE}")
    if kill -0 $PID >/dev/null 2>&1; then
      return
    fi
    rm -f "${PID_FILE}" >/dev/null
  fi
  return 1
}

case $1 in
start)
  if status; then
    echo "${SERVICE_NAME} is already running"
    exit 0
  else
    echo "Starting ${SERVICE_NAME} ..."
    tun_created
    start
    exit $?
  fi
  ;;
stop)
  if status; then
    echo "Stopping ${SERVICE_NAME} ..."
    stop
    exit $?
  else
    echo "${SERVICE_NAME} is not running"
    exit 0
  fi
  ;;
status)
  if status; then
    echo "${SERVICE_NAME} is running"
    exit 0
  else
    echo "${SERVICE_NAME} is not running"
    exit 3
  fi
  ;;
*)
  echo "command $1 is not implemented"
  exit 0
  ;;
esac
